### ISSUE TITLE
Wrong version displayed

### ISSUE THREAD

**Issue by ilanschnell** [Anaconda-Server/conda-server#122]
```
$ conda list binstar
# packages in environment at /home/ilan/minonda:
#
binstar                   0.10.1                   py27_1 
```
However:
```
$ binstar --version
binstar Command line client (version 0.8)
```
In the code, I see:
```
try:
    from ._version import __version__
except:
    __version__ = '0.8'
```
However, `_version.py` does not exist.  I would recommend using versioneer.

**Comment by srossross** [comment]
@ilanschnell are you using the existing conda.recipe when you create the binstar package?

**Comment by ilanschnell** [comment]
Ah, I see now what the recipe is doing with `make_version.py`.  I would still recommend using versioneer.  conda, iopro, numba and several other of our projects use it and we never run into any problems.  All that needs to be done for a release it to git tag.

**Comment by srossross** [comment]
Thanks @ilanschnell, I will start using versioneer.

**Comment by ilanschnell** [comment]
I tried using `make_version.py`, but I get an error on Python 3.  So switching to versioneer will be a good thing.

**Comment by tswicegood** [comment]
... cleaning out my inbox ...

FWIW, I have an open PR binstar-build (https://github.com/Binstar/binstar-build/pull/26) that solves this problem in a way that works well for bumping to alpha/dev versions without tags.

**Comment by malev** [comment]
This should be fixed by now
