### ISSUE TITLE
Can't upload packages with numbers at beginning of name

### ISSUE THREAD

**Issue by xxyyx** [Anaconda-Server/conda-server#19]
Packages with numbers at start of name raise an error:

$ binstar upload 9ML-0.1.0.tar.gz 
detecting package type ... conda
extracting package attributes for upload ... done
BinstarError: package name 4ml not valid

Tried it with a few others; 4chan, 42qucc, 2mp4 and they all have the same error

**Comment by malev** [comment]
seems to be working now, closing
